/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gt.edu.url.compiladores.prueba1;

/**
 *
 * @author Toshiba
 */
public enum Token {
    Desde,
    SiNo,
    Exponente,
    OPARBool,
    FunESPReal,
    CadenaAEntero,
    CadenaABoleano,
    Eliminar,
    Destructor,
    Incluir,
    Estatico,
    Linea,
    ErrorNum,
    NameClass,
    Comentario,
    Comillas,
    Coma,
    T_dato,
    T_Disponible,
    Cadena,
    Nulo,
    Si,
    Sino,
    Hacer,
    Mientras,
    Para,
    Devolver,
    Igual,
    Suma,
    Resta,
    Multiplicacion,
    Division,
    Mod,
    Op_logico,
    Op_incremento,
    Op_relacional,
    Op_atribucion,
    Op_booleano,
    Parentesis_a,
    Parentesis_c,
    Punto,
    Leer,
    Llave_a,
    Llave_c,
    Lexer,
    Corchete_a,
    Corchete_c,
    Constructor,
    Principal,
    Metodo,
    Propiedad,
    Clase,
    P_coma,
    Instanciar,
    Identificador,
    Numero,
    Escribir,
    Entero,
    Dos_puntos,
    Boleano,
    Entonces,
    BEsp,
    ERROR
}
