
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package gt.edu.url.compiladores.prueba1;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int CADaBOOL = 59;
  public static final int BOOLTEXT = 23;
  public static final int ELIMINAR = 56;
  public static final int COMILLAS = 3;
  public static final int IDENTIFICADOR = 65;
  public static final int OPATRIBUCION = 15;
  public static final int DIVISION = 11;
  public static final int REAL = 30;
  public static final int FUNespREAL = 58;
  public static final int EXPONENTE = 28;
  public static final int SI = 35;
  public static final int CONSTRUCTOR = 47;
  public static final int TEXTO = 82;
  public static final int CORCHETEC = 22;
  public static final int CORCHETEA = 21;
  public static final int LEER = 44;
  public static final int PROPIEDAD = 50;
  public static final int METODO = 49;
  public static final int NUMERO = 63;
  public static final int ERRORNAMECLASS = 78;
  public static final int ERRORCOM = 70;
  public static final int OPARBOOL = 29;
  public static final int OPBOLEANO = 25;
  public static final int ERRORID = 77;
  public static final int FINLINEA = 2;
  public static final int NAMECLASS = 54;
  public static final int HACER = 39;
  public static final int PARA = 41;
  public static final int MOD = 12;
  public static final int SIGUAL = 7;
  public static final int FINSI = 38;
  public static final int CADTEXTO = 66;
  public static final int COMA = 27;
  public static final int ENTERO = 33;
  public static final int ERROREAL = 72;
  public static final int DOBLEIGUAL = 4;
  public static final int OPRELACIONAL = 14;
  public static final int CLASE = 53;
  public static final int DECIMAL = 64;
  public static final int DOSPUNTOS = 13;
  public static final int PUNTOYCOMA = 26;
  public static final int INCLUIR = 60;
  public static final int ERRORSIGNOS2 = 81;
  public static final int ERRORSIGNOS1 = 80;
  public static final int ERROROPARBO = 75;
  public static final int CADENAaENTERO = 57;
  public static final int ERRORDECIM = 69;
  public static final int NULO = 32;
  public static final int EOF = 0;
  public static final int MIENTRAS = 40;
  public static final int PUNTO = 6;
  public static final int SUMA = 8;
  public static final int DEVOLVER = 42;
  public static final int ERRORSIGNOS = 79;
  public static final int ERRORARIT = 73;
  public static final int ERRORCERO = 67;
  public static final int PRINCIPAL = 46;
  public static final int DESTRUCTOR = 48;
  public static final int ERRORSIG = 76;
  public static final int error = 1;
  public static final int RESTA = 9;
  public static final int EXTENCIONBIB = 61;
  public static final int ERRORSIGP = 74;
  public static final int ENTONCES = 36;
  public static final int TDISPONIBLEP = 52;
  public static final int SINO = 37;
  public static final int TDISPONIBLEM = 51;
  public static final int MULTIPLICACION = 10;
  public static final int PARENTESISC = 18;
  public static final int PARENTESISA = 17;
  public static final int ERROROPINC = 71;
  public static final int ESTATICO = 62;
  public static final int INSTANCIAR = 55;
  public static final int OPINCREMENTO = 16;
  public static final int CADENA = 31;
  public static final int NEGAR = 5;
  public static final int BOLEANO = 34;
  public static final int ERRORNUM = 68;
  public static final int ESCRIBIR = 45;
  public static final int LLAVEC = 20;
  public static final int LLAVEA = 19;
  public static final int DESDE = 43;
  public static final int BOOLNUM = 24;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "FINLINEA",
  "COMILLAS",
  "DOBLEIGUAL",
  "NEGAR",
  "PUNTO",
  "SIGUAL",
  "SUMA",
  "RESTA",
  "MULTIPLICACION",
  "DIVISION",
  "MOD",
  "DOSPUNTOS",
  "OPRELACIONAL",
  "OPATRIBUCION",
  "OPINCREMENTO",
  "PARENTESISA",
  "PARENTESISC",
  "LLAVEA",
  "LLAVEC",
  "CORCHETEA",
  "CORCHETEC",
  "BOOLTEXT",
  "BOOLNUM",
  "OPBOLEANO",
  "PUNTOYCOMA",
  "COMA",
  "EXPONENTE",
  "OPARBOOL",
  "REAL",
  "CADENA",
  "NULO",
  "ENTERO",
  "BOLEANO",
  "SI",
  "ENTONCES",
  "SINO",
  "FINSI",
  "HACER",
  "MIENTRAS",
  "PARA",
  "DEVOLVER",
  "DESDE",
  "LEER",
  "ESCRIBIR",
  "PRINCIPAL",
  "CONSTRUCTOR",
  "DESTRUCTOR",
  "METODO",
  "PROPIEDAD",
  "TDISPONIBLEM",
  "TDISPONIBLEP",
  "CLASE",
  "NAMECLASS",
  "INSTANCIAR",
  "ELIMINAR",
  "CADENAaENTERO",
  "FUNespREAL",
  "CADaBOOL",
  "INCLUIR",
  "EXTENCIONBIB",
  "ESTATICO",
  "NUMERO",
  "DECIMAL",
  "IDENTIFICADOR",
  "CADTEXTO",
  "ERRORCERO",
  "ERRORNUM",
  "ERRORDECIM",
  "ERRORCOM",
  "ERROROPINC",
  "ERROREAL",
  "ERRORARIT",
  "ERRORSIGP",
  "ERROROPARBO",
  "ERRORSIG",
  "ERRORID",
  "ERRORNAMECLASS",
  "ERRORSIGNOS",
  "ERRORSIGNOS1",
  "ERRORSIGNOS2",
  "TEXTO"
  };
}

